services:
  playlistdl:
    image: thomaboehi/playlistdlwithapi:latest
    container_name: PlaylistDLWithAPI_TEST
    healthcheck:
      test: ["CMD-SHELL", "nc -z 127.0.0.1 5000 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 90s
    ports:
      - "5005:5000"
    environment:
      #User ID for permission
      - USER_ID: 1000
      - GROUP_USER_ID: 1000
      #Follow mariushosting tutorial on how to get user ID on Synology NAS if you host on NAS.
      # https://mariushosting.com/synology-find-uid-userid-and-gid-groupid-in-5-seconds/
      - AUDIO_DOWNLOAD_PATH=/your/local/path  # Use the env variable
      - CLEANUP_INTERVAL=300  # Optional
    volumes:
      - /your/local/path:/your/local/path:rw  # Reference env variable here as well
    restart: unless-stopped